[2024-08-28T10:11:29.739+0200] {processor.py:153} INFO - Started process (PID=74944) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:11:29.740+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:11:29.742+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:11:29.741+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:11:29.761+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:11:29.760+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:11:29.761+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:11:29.761+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:11:29.762+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:11:29.769+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-08-28T10:12:11.451+0200] {processor.py:153} INFO - Started process (PID=75007) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:12:11.453+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:12:11.453+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:12:11.453+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:12:11.466+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:12:11.465+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:12:11.466+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:12:11.466+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:12:11.467+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:12:11.473+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-28T10:12:53.174+0200] {processor.py:153} INFO - Started process (PID=75076) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:12:53.176+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:12:53.178+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:12:53.177+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:12:53.198+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:12:53.197+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:12:53.199+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:12:53.199+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:12:53.199+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:12:53.209+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-08-28T10:13:35.108+0200] {processor.py:153} INFO - Started process (PID=75127) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:13:35.110+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:13:35.111+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:13:35.111+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:13:35.128+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:13:35.128+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:13:35.129+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:13:35.128+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:13:35.129+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:13:35.136+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-08-28T10:14:17.514+0200] {processor.py:153} INFO - Started process (PID=75206) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:14:17.516+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:14:17.518+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:14:17.517+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:14:17.542+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:14:17.541+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:14:17.543+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:14:17.543+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:14:17.543+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:14:17.551+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-08-28T10:15:00.584+0200] {processor.py:153} INFO - Started process (PID=75252) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:15:00.586+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:15:00.587+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:15:00.587+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:15:00.609+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:15:00.608+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:15:00.610+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:15:00.610+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:15:00.610+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:15:00.621+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-08-28T10:15:41.722+0200] {processor.py:153} INFO - Started process (PID=75297) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:15:41.724+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:15:41.725+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:15:41.725+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:15:41.746+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:15:41.745+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:15:41.747+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:15:41.746+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:15:41.747+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:15:41.755+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-08-28T10:16:19.874+0200] {processor.py:153} INFO - Started process (PID=75341) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:16:19.876+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:16:19.877+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:16:19.877+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:16:19.895+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:16:19.894+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:16:19.895+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:16:19.895+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:16:19.896+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:16:19.904+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-08-28T10:17:02.074+0200] {processor.py:153} INFO - Started process (PID=75387) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:17:02.076+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:17:02.078+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:17:02.077+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:17:02.096+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:17:02.095+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:17:02.097+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:17:02.096+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:17:02.097+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:17:02.105+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-08-28T10:17:42.955+0200] {processor.py:153} INFO - Started process (PID=75442) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:17:42.956+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:17:42.957+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:17:42.956+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:17:42.968+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:17:42.968+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:17:42.969+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:17:42.969+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:17:42.969+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:17:42.976+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28T10:44:05.944+0200] {processor.py:153} INFO - Started process (PID=75539) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:44:05.945+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:44:05.946+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:44:05.946+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:44:05.961+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:44:05.960+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:44:05.962+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:44:05.961+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:44:05.962+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:44:05.973+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-08-28T10:44:48.628+0200] {processor.py:153} INFO - Started process (PID=75597) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:44:48.630+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:44:48.632+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:44:48.631+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:44:48.653+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:44:48.652+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:44:48.654+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:44:48.654+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:44:48.654+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:44:48.663+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-08-28T10:45:30.669+0200] {processor.py:153} INFO - Started process (PID=75649) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:45:30.670+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:45:30.671+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:45:30.671+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:45:30.684+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:45:30.683+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:45:30.684+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:45:30.684+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:45:30.684+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:45:30.691+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28T10:46:10.253+0200] {processor.py:153} INFO - Started process (PID=75694) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:46:10.255+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:46:10.256+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:46:10.256+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:46:10.275+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:46:10.274+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:46:10.276+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:46:10.276+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:46:10.276+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:46:10.285+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-08-28T10:46:51.589+0200] {processor.py:153} INFO - Started process (PID=75743) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:46:51.591+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:46:51.592+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:46:51.592+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:46:51.612+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:46:51.611+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:46:51.613+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:46:51.612+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:46:51.613+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:46:51.622+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-08-28T10:47:33.310+0200] {processor.py:153} INFO - Started process (PID=75795) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:47:33.313+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:47:33.315+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:47:33.314+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:47:33.333+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:47:33.333+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:47:33.334+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:47:33.333+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:47:33.334+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:47:33.341+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-08-28T10:48:15.387+0200] {processor.py:153} INFO - Started process (PID=75858) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:48:15.389+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:48:15.391+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:48:15.390+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:48:15.410+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:48:15.409+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:48:15.410+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:48:15.410+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:48:15.410+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:48:15.417+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-08-28T10:48:56.751+0200] {processor.py:153} INFO - Started process (PID=75916) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:48:56.754+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:48:56.756+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:48:56.755+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:48:56.778+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:48:56.777+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:48:56.779+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:48:56.779+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:48:56.779+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:48:56.787+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2024-08-28T10:49:38.215+0200] {processor.py:153} INFO - Started process (PID=75962) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:49:38.217+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:49:38.219+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:49:38.218+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:49:38.243+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:49:38.242+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:49:38.243+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:49:38.243+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:49:38.244+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:49:38.251+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-08-28T10:50:19.038+0200] {processor.py:153} INFO - Started process (PID=76007) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:50:19.040+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:50:19.041+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:50:19.041+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:50:19.052+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:50:19.052+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:50:19.053+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:50:19.053+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:50:19.053+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:50:19.060+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28T10:50:59.528+0200] {processor.py:153} INFO - Started process (PID=76056) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:50:59.530+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:50:59.531+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:50:59.531+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:50:59.553+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:50:59.552+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:50:59.554+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:50:59.554+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:50:59.555+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:50:59.563+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-08-28T10:51:42.900+0200] {processor.py:153} INFO - Started process (PID=76113) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:51:42.902+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:51:42.903+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:51:42.903+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:51:42.922+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:51:42.921+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:51:42.923+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:51:42.922+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:51:42.923+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:51:42.932+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-08-28T10:52:21.970+0200] {processor.py:153} INFO - Started process (PID=76167) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:52:21.976+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:52:21.978+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:52:21.977+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:52:22.020+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:52:22.020+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:52:22.021+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:52:22.020+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:52:22.021+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:52:22.026+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-08-28T10:53:04.880+0200] {processor.py:153} INFO - Started process (PID=76214) to work on /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:53:04.881+0200] {processor.py:743} INFO - Processing file /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28T10:53:04.882+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:53:04.881+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:53:04.892+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:53:04.891+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28T10:53:04.892+0200] {logging_mixin.py:137} INFO - [2024-08-28T10:53:04.892+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28T10:53:04.893+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28T10:53:04.899+0200] {processor.py:175} INFO - Processing /Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
